package com.example.spgtu.util.type;

public enum  WaitingType {
    START, START_DATE,
    CHOOSE_OPTION,
    END_DATE,
    COMMAND_EDITOR,
    UPDATE_BUTTON,
    UPDATE_TEXT,
    UPDATE_FILE,
    UPDATE_BUTTON_LINK,
    SET_FULL_NAME,GET_CERTIFICATE, SUGGESTION, COMPLAINT, CHOOSE_SURVEY, CHOOSE_OPTION_SURVEY, SET_NAME_RU, SET_NAME_KZ, SET_QUEST_RU,
    SET_QUEST_KZ, SET_LOCATION,EIGHTEEN, SET_ANSWER_OF_QUEST_RU, SET_ANSWER_OF_QUEST_KZ, LEVEL_OF_EDUCATION, FULL_NAME_INSTITUTE, SPECIALTY, RECEIPT_DATE,
    EXPIRATION_DATE,FACULTY,EDUCATION_FORM,PREPARATION_CODE,TRAINING_DIRECTION,EDUCATION,ADDRESS,FATHERS_NAME,FATHERS_CONTACTS,MOTHERS_NAME,MOTHERS_CONTACTS, NAME_OF_COMPANY,SEVENTEEN,SURNAME,FIO,GENDER,CITIZENSHIP,MARITAL_STATUS,SOCIAL_STATUS,UNIVERNAME_CITY_DISTRICT, POSITION, INDUSTRY, DEVICE_DATE, DATE_OF_DISMISSAL, CAREER_OBJECTIVE,
    HOME_PHONE_NUMBER, SET_PHONE_NUMBER, REASON, CONFIRM, INSERT_FIO, E_MAIL, CHOOSE_SURVEY_FOR_EDIT, UPDATE_SURVEY, UPDATE_QUEST, QUEST_EDITION, SET_NEW_NAME,
    EDITION, SET_NEW_QUEST_TEXT,SIXTEEN,NINETEEN, DELETE,FIFTEEN, GET_RANGE, SET_RANGE, DELETE_QUEST, SET_QUESTION, SET_EMAIL,SET_FULLNAME,SET_IIN,SET_FONE,
    CHOOSE_USER, SUBSCRIBE, SUBSCRIBE2,FOLLOW,UNFOLLOW,SET_DATE,ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,EIGHT,NINE,TEN,BUTTON_EDITION_NAME,
    BUTTON_EDITION_MESSAGE,DELETE_FILE,LAST,ADD_FILE,INTERNAL_MENU,COURSES,SEMINARS,CONTESTS,ADDING,GET_INFO,SELECTING,SAVE,NAME_EDIT,DESCRIPTION_EDIT,SALARY_EDIT,
    TURN_OFF_ON,PRICE_EDIT, FREE, ELEVEN,EDIT_NAME, TWELVE, DURATION_EDIT,GET_CANCEL_TEXT,KZ_NAME,RU_NAME,SET_FILE,GET_FILES
    ,SELECT_MODE,GET_REQUESTED_LIST,FOURTEEN,THIRTEEN, BACK, GET_FIO ,GET_LIST_FILE,ADD_LIST_FILE,UPDATE_LIST_FILE,DELETE_ALL,EDIT_KAZ_NAME,EDIT_RU_NAME,EDIT_COURSE_KZ_DESCRIPTION,

    EDIT_COURSE_RU_DESCRIPTION,ADD_LESSON_FILE_RU_NAME,ADD_LESSON_FILE_KZ_NAME,ADD_LESSON_FILE,ADD_PHOTO,DELETE_PHOTO,
    CHOOSE_VARIANT,
    ADD_COURSE_KZ_NAME,ADD_COURSE_RU_NAME,GET_PHOTO,ADD_COURSE_KZ_DESC,ADD_COURSE_RU_DESC,ADD_COURSE_PRICE,ADD_COURSE_DURATION,SECOND_SELECT, SELECT_VARIANT,SEND_REQUEST,
    SELECT_COURSE, SET_TEXT, EDIT_LESSON_RU_NAME,GET_PHONE_NUMBER, EDIT_LESSON_KZ_NAME, EDIT_FILE_RU_NAME, EDIT_FILE_KZ_NAME,GET_STATUS, GET_IIN, SAVE_STUDENT, GET_CHOOSEN_LESSON, SET_COURSE, PRICE, SELECTED_STATUS, IIN_NUMBER, EDU_DIRECTION, GET_IIN_NUMBER, SET_IIN_NUMBER, EDIT_IIN_NUMBER, SEARCH_BUTTON, COUNT_HOURS, SET_NUMBER_CARD, WHO_GIVE, INFORMED, NATIONALITY, YES_OR_NO, SELECT_EDUCATION, SET_CARD_ID, DATE_ISSUE, DATE_END, ISSUED_BY, PHOTO_CARD, PHOTO_CARD_BACK, PHOTO, SELECT_ROOM, DATE_START, CHOOSE_DORM, CHOOSE_WHO, CONFIRM2, SET_PERIOD, CONFIRM_DATE, SET_LOGIN, SET_PASSWORD, SET_VEDOMOST, PAY_VEDOMOST;
}
